"""ITR helpers — printable PDF for CA handoff + JSON exports.

The JSON structures mirror (closely — not bit-exact) the schemas used by
Income-Tax-India's JSON upload utility for Schedule CG and Schedule FA. Any
final filing MUST be regenerated by the CA against the current Finance-Act
schema; this module is advisory.
"""

from __future__ import annotations

import io
from dataclasses import asdict
from decimal import Decimal
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    _HAS_REPORTLAB = True
except Exception:  # pragma: no cover
    _HAS_REPORTLAB = False

from pfip.tax.engine import (
    CGEvent,
    Form67Row,
    GainTerm,
    ScheduleFARow,
    TaxSummary,
)
from pfip.tax.indian_rules import DISCLAIMER


def _d(v: Any) -> str:
    """Decimal-to-string with 2 dp for human display."""
    if v is None:
        return "0.00"
    try:
        return f"{Decimal(str(v)):,.2f}"
    except Exception:
        return str(v)


def schedule_cg_json(events: list[CGEvent]) -> dict:
    """ITR-2/ITR-3 Schedule CG JSON-like structure.

    Split out STCG / LTCG and per-asset-class totals.
    """
    stcg_eq = [
        e
        for e in events
        if e.term == GainTerm.STCG and e.asset_class.value in ("equity", "equity_mf")
    ]
    ltcg_eq = [
        e
        for e in events
        if e.term == GainTerm.LTCG and e.asset_class.value in ("equity", "equity_mf")
    ]
    vda = [e for e in events if e.asset_class.value == "vda"]
    debt = [e for e in events if e.asset_class.value in ("debt", "debt_mf")]

    def _row(e: CGEvent) -> dict:
        return {
            "symbol": e.symbol,
            "asset_class": e.asset_class.value,
            "qty": str(e.qty),
            "buy_date": e.buy_date.isoformat(),
            "sell_date": e.sell_date.isoformat(),
            "cost_basis_inr": str(e.buy_cost_inr),
            "proceeds_inr": str(e.sell_proceeds_inr),
            "gain_inr": str(e.gain_inr),
            "grandfathered": e.grandfathered,
            "tds_inr": str(e.tds_inr),
        }

    total_stcg = sum((e.gain_inr for e in stcg_eq), Decimal("0"))
    total_ltcg = sum((e.gain_inr for e in ltcg_eq), Decimal("0"))
    total_vda = sum((e.gain_inr for e in vda), Decimal("0"))
    total_debt = sum((e.gain_inr for e in debt), Decimal("0"))

    return {
        "schedule": "CG",
        "equity_stcg": {
            "section": "111A",
            "items": [_row(e) for e in stcg_eq],
            "total_gain_inr": str(total_stcg),
        },
        "equity_ltcg": {
            "section": "112A",
            "items": [_row(e) for e in ltcg_eq],
            "total_gain_inr": str(total_ltcg),
        },
        "vda": {
            "section": "115BBH",
            "items": [_row(e) for e in vda],
            "total_gain_inr": str(total_vda),
            "loss_setoff_allowed": False,
        },
        "debt": {
            "items": [_row(e) for e in debt],
            "total_gain_inr": str(total_debt),
        },
        "disclaimer": DISCLAIMER,
    }


def schedule_fa_json(rows: list[ScheduleFARow]) -> dict:
    """Schedule FA JSON-like structure."""
    return {
        "schedule": "FA",
        "rows": [
            {
                "country": r.country,
                "symbol": r.symbol,
                "isin": r.isin,
                "acquired_on": r.acquired_on.isoformat() if r.acquired_on else None,
                "peak_balance_usd": str(r.peak_balance_usd),
                "peak_balance_inr": str(r.peak_balance_inr),
                "closing_balance_usd": str(r.closing_balance_usd),
                "closing_balance_inr": str(r.closing_balance_inr),
                "gross_interest_usd": str(r.gross_interest_usd),
                "gross_dividend_usd": str(r.gross_dividend_usd),
                "gross_proceeds_usd": str(r.gross_proceeds_usd),
            }
            for r in rows
        ],
        "disclaimer": DISCLAIMER,
    }


def form_67_json(rows: list[Form67Row]) -> dict:
    """Form 67 JSON-like structure."""
    total_credit = sum((r.dtaa_credit_inr for r in rows), Decimal("0"))
    return {
        "form": "67",
        "rows": [
            asdict(r) | {k: str(v) for k, v in asdict(r).items() if isinstance(v, Decimal)}
            for r in rows
        ],
        "total_dtaa_credit_inr": str(total_credit),
        "disclaimer": DISCLAIMER,
    }


# ---------------------------------------------------------------------------
# Printable PDF summary
# ---------------------------------------------------------------------------


def build_summary_pdf(
    summary: TaxSummary,
    events: list[CGEvent] | None = None,
    fa_rows: list[ScheduleFARow] | None = None,
    f67_rows: list[Form67Row] | None = None,
) -> bytes:
    """Return a single-page A4 PDF summary suitable for CA handoff.

    Falls back to a plain-text bytes buffer if reportlab is unavailable.
    """
    if not _HAS_REPORTLAB:
        lines = [
            f"PFIP TAX SUMMARY — FY {summary.fy}",
            "",
            f"Disclaimer: {DISCLAIMER}",
            "",
            f"Equity STCG: Rs. {_d(summary.stcg_equity_inr)}",
            f"Equity LTCG (pre-exempt): Rs. {_d(summary.ltcg_equity_inr)}",
            f"VDA gains: Rs. {_d(summary.vda_gain_inr)} | TDS credit: Rs. {_d(summary.vda_tds_inr)}",
            f"Dividend: Rs. {_d(summary.dividend_inr)}",
            f"Total tax (advisory): Rs. {_d(summary.total_tax_inr)}",
            f"Recommended regime: {summary.recommended_regime.upper()}",
            f"Recommended ITR: {summary.recommended_itr}",
        ]
        return ("\n".join(lines)).encode("utf-8")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title=f"PFIP Tax Summary FY {summary.fy}")
    styles = getSampleStyleSheet()
    story: list = []
    story.append(Paragraph(f"<b>PFIP Tax Summary — FY {summary.fy}</b>", styles["Title"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<i>{DISCLAIMER}</i>", styles["Italic"]))
    story.append(Spacer(1, 12))

    head_data = [
        ["Metric", "Amount (INR)"],
        ["Equity STCG (gains)", _d(summary.stcg_equity_inr)],
        ["Equity LTCG (gains, pre-exempt)", _d(summary.ltcg_equity_inr)],
        ["VDA gains (taxable)", _d(summary.vda_gain_inr)],
        ["VDA TDS credit", _d(summary.vda_tds_inr)],
        ["Dividend (gross)", _d(summary.dividend_inr)],
        ["Interest (gross)", _d(summary.interest_inr)],
        ["Total estimated tax", _d(summary.total_tax_inr)],
        ["Recommended regime", summary.recommended_regime.upper()],
        ["Recommended ITR", summary.recommended_itr],
    ]
    t = Table(head_data, hAlign="LEFT", colWidths=[220, 160])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(t)

    if summary.surcharge_cliff_warnings:
        story.append(Spacer(1, 12))
        story.append(Paragraph("<b>Surcharge-cliff warnings</b>", styles["Heading3"]))
        for w in summary.surcharge_cliff_warnings:
            story.append(Paragraph("• " + w, styles["BodyText"]))

    if events:
        story.append(Spacer(1, 12))
        story.append(Paragraph("<b>Capital-gains events (first 20)</b>", styles["Heading3"]))
        rows = [["Symbol", "Term", "Sell", "Qty", "Cost", "Proceeds", "Gain"]]
        for e in events[:20]:
            rows.append(
                [
                    e.symbol,
                    e.term.value,
                    e.sell_date.isoformat(),
                    str(e.qty),
                    _d(e.buy_cost_inr),
                    _d(e.sell_proceeds_inr),
                    _d(e.gain_inr),
                ]
            )
        story.append(
            Table(
                rows,
                hAlign="LEFT",
                style=TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ]
                ),
            )
        )
    if fa_rows:
        story.append(Spacer(1, 12))
        story.append(Paragraph("<b>Schedule FA</b>", styles["Heading3"]))
        rows = [["Symbol", "Peak USD", "Peak INR", "Closing USD", "Dividends USD"]]
        for r in fa_rows:
            rows.append(
                [
                    r.symbol,
                    _d(r.peak_balance_usd),
                    _d(r.peak_balance_inr),
                    _d(r.closing_balance_usd),
                    _d(r.gross_dividend_usd),
                ]
            )
        story.append(Table(rows, hAlign="LEFT"))
    if f67_rows:
        story.append(Spacer(1, 12))
        story.append(Paragraph("<b>Form 67 (DTAA credit)</b>", styles["Heading3"]))
        rows = [["Source", "Foreign income INR", "Tax abroad INR", "Credit INR"]]
        for r in f67_rows:
            rows.append(
                [
                    r.source_name,
                    _d(r.foreign_income_inr),
                    _d(r.tax_paid_abroad_inr),
                    _d(r.dtaa_credit_inr),
                ]
            )
        story.append(Table(rows, hAlign="LEFT"))

    doc.build(story)
    return buf.getvalue()
